import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

import java.util.List;

/**
 * list of city's forecasts (class was generated by jsonschema2pojo )
 */
class IpmaCityForecast {

        @SerializedName("owner")
        @Expose
        private String owner;
        @SerializedName("country")
        @Expose
        private String country;
        @SerializedName("data")
        @Expose
        private List<CityForecast> data = null;
        @SerializedName("globalIdLocal")
        @Expose
        private Integer globalIdLocal;
        @SerializedName("dataUpdate")
        @Expose
        private String dataUpdate;

    /**
     * Get the name of information provider.
     * @return
     */
    public String getOwner() {
            return owner;
        }

    /**
     * Owner setter.
     * @param owner
     */
        public void setOwner(String owner) {
            this.owner = owner;
        }

    /**
     * Get the name of country.
     * @return country
     */
        public String getCountry() {
            return country;
        }

    /**
     * Country setter.
     * @param country
     */
        public void setCountry(String country) {
            this.country = country;
        }

    /**
     * Get the forecast for the ID we want
     * @return forecast
     */
        public List<CityForecast> getData() {
            return data;
        }

    /**
     * Data setter.
     * @param data
     */
        public void setData(List<CityForecast> data) {
            this.data = data;
        }

    /**
     * Get the Global ID
     * @return globalID
     */
    public Integer getGlobalIdLocal() {
            return globalIdLocal;
        }

    /**
     * Global ID setter.
     * @param globalIdLocal
     */
    public void setGlobalIdLocal(Integer globalIdLocal) {
            this.globalIdLocal = globalIdLocal;
        }

    /**
     * Get the date of the last update.
     * @return date of the last update
     */
        public String getDataUpdate() {
            return dataUpdate;
        }

    /**
     * Setter of date update.
     * @param dataUpdate
     */
    public void setDataUpdate(String dataUpdate) {
            this.dataUpdate = dataUpdate;
        }
}

/**
 * the data point with the forecast for a city in a day
 */
class CityForecast {

    @SerializedName("precipitaProb")
    @Expose
    private String precipitaProb;
    @SerializedName("tMin")
    @Expose
    private String tMin;
    @SerializedName("tMax")
    @Expose
    private String tMax;
    @SerializedName("predWindDir")
    @Expose
    private String predWindDir;
    @SerializedName("idWeatherType")
    @Expose
    private Integer idWeatherType;
    @SerializedName("classWindSpeed")
    @Expose
    private Integer classWindSpeed;
    @SerializedName("longitude")
    @Expose
    private String longitude;
    @SerializedName("forecastDate")
    @Expose
    private String forecastDate;
    @SerializedName("latitude")
    @Expose
    private String latitude;

    /**
     * Gets the probability of precipitation.
     * @return probability of precipitation
     */
    public String getPrecipitaProb() {
        return precipitaProb;
    }

    /**
     * Precitipation Probability Setter.
     * @param precipitaProb
     */
    public void setPrecipitaProb(String precipitaProb) {
        this.precipitaProb = precipitaProb;
    }

    /**
     * Gets the Min Temperature for the location.
     * @return min temperature
     */
    public String getTMin() {
        return tMin;
    }

    /**
     * Min Temp setter.
     * @param tMin
     */
    public void setTMin(String tMin) {
        this.tMin = tMin;
    }

    /**
     * Gets the max temperature for the location.
     * @return max temperature
     */
    public String getTMax() {
        return tMax;
    }

    /**
     * Max temperature setter.
     * @param tMax
     */
    public void setTMax(String tMax) {
        this.tMax = tMax;
    }

    /**
     * Gets win direction.
     * @return win direction
     */
    public String getPredWindDir() {
        return predWindDir;
    }

    /**
     * Set window direction.
     * @param predWindDir
     */
    public void setPredWindDir(String predWindDir) {
        this.predWindDir = predWindDir;
    }

    /**
     * Get weather id.
     * @return weather id
     */
    public Integer getIdWeatherType() {
        return idWeatherType;
    }

    /**
     * Weather Type setter.
     * @param idWeatherType
     */
    public void setIdWeatherType(Integer idWeatherType) {
        this.idWeatherType = idWeatherType;
    }

    /**
     * Get win speed.
     * @return win speed.
     */
    public Integer getClassWindSpeed() {
        return classWindSpeed;
    }

    /**
     * Win speed setter.
     * @param classWindSpeed
     */
    public void setClassWindSpeed(Integer classWindSpeed) {
        this.classWindSpeed = classWindSpeed;
    }

    /**
     * Get longitude.
     * @return longitude
     */
    public String getLongitude() {
        return longitude;
    }

    /**
     * Longitude setter.
     * @param longitude
     */
    public void setLongitude(String longitude) {
        this.longitude = longitude;
    }

    /**
     * Get forecast date.
     * @return forecast date
     */
    public String getForecastDate() {
        return forecastDate;
    }

    /**
     * Forecast date setter.
     * @param forecastDate
     */
    public void setForecastDate(String forecastDate) {
        this.forecastDate = forecastDate;
    }

    /**
     * Get latitude.
     * @return latitude
     */
    public String getLatitude() {
        return latitude;
    }

    /**
     * Latitude setter.
     * @param latitude
     */
    public void setLatitude(String latitude) {
        this.latitude = latitude;
    }
}

class IPMAInformation
{
    @SerializedName("local")
    @Expose
    private String local;

    @SerializedName("globalIdLocal")
    @Expose
    private String globalIdLocal;

    @SerializedName("data")
    @Expose
    private List<IPMAInformation> data = null;

    /**
     * Get the ID given a name.
     * @return ID if the name exists,
     * otherwise null.
     */
    public String getData(String city) {
        for (IPMAInformation a : data){
            if (a.getLocal().equals(city)){
                return a.getGlobalIdLocal();
            }
        }
        return null;
    }

    /**
     * Get the local.
     *
     * @return local
     */
    public String getLocal() {
        return local;
    }

    /**
     * Local setter.
     * @param local
     */
    public void setLocal(String local) {
        this.local = local;
    }

    /**
     * Gets global id.
     * @return global id
     */
    public String getGlobalIdLocal() {
        return globalIdLocal;
    }

    /**
     * Global id setter.
     * @param globalIdLocal
     */
    public void setGlobalIdLocal(String globalIdLocal) {
        this.globalIdLocal = globalIdLocal;
    }
}